/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dbutakov' at '10/15/16 12:10 AM' with Gradle 3.1
 *
 * @author dbutakov, @date 10/15/16 12:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
