import org.junit.Test;
import org.junit.Ignore;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
//import static org.hamcrest.MatcherAssert.assertThat;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dbutakov' at '10/15/16 12:10 AM' with Gradle 3.1
 *
 * @author dbutakov, @date 10/15/16 12:10 AM
 */
public class LibraryAcceptanceTest {
  @Test
  public void test_positive_case_namesurname() {
      Library classUnderTest = new Library();
      assertThat(classUnderTest.someLibraryMethod(true), is(false));
  }
  @Test
  public void test_negative() {
      Library classUnderTest = new Library();
      assertThat(classUnderTest.someLibraryMethod(false), is(false));
  }

  @Test
  public void alwaysFail() {
    fail();
  }
}
